CONFIG = {
    "name": "anime",
    "display_name": "Top Anime (MyAnimeList)",
    "sample_size": 0,
    "sample_seed": 42,
    "embedding_columns": ["score", "members", "episodes", "type", "source", "genre_primary", "rating"],
    "color_columns": ["genre_primary", "type", "source", "rating"],
    "filter_columns": ["genre_primary", "genres", "type", "source", "rating"],
    "tooltip_columns": ["title_english", "score", "episodes", "type", "genres", "studios", "year", "members", "source", "rating"],
    "default_color": "genre_primary",
    "range_column": "score",
    "range_label": "Score",
    "label_column": "title_english",
    "image_column": "image_url",
    "multi_value_columns": ["genres", "studios"],
    "embedding_mode": "text-gemini",
    "reducer": "umap",
    "umap_n_neighbors": 20,
    "umap_min_dist": 0.35,
    "umap_metric": "cosine",
    "n_clusters": 8,
}
