CONFIG = {
    "name": "ecommerce",
    "display_name": "E-commerce Products",
    "sample_size": 0,
    "sample_seed": 42,
    "embedding_columns": ["price", "rating", "stock", "discountPercentage", "category"],
    "color_columns": ["category"],
    "filter_columns": ["category"],
    "tooltip_columns": ["title", "price", "rating", "discountPercentage", "stock", "category", "brand"],
    "default_color": "category",
    "range_column": "price",
    "label_column": "title",
    "image_column": "thumbnail",
    "embedding_mode": "text-gemini",
    "reducer": "umap",
    "umap_n_neighbors": 15,
    "umap_min_dist": 0.35,
    "umap_metric": "cosine",
    "n_clusters": 5,
}
