CONFIG = {
    "name": "met_museum",
    "display_name": "Art Institute of Chicago",
    "sample_size": 2000,
    "sample_seed": 42,
    "embedding_columns": ["department", "culture", "classification", "artworkType", "style"],
    "color_columns": ["department", "artworkType", "classification"],
    "filter_columns": ["department", "artworkType"],
    "tooltip_columns": ["title", "artistDisplayName", "objectDate", "medium", "department", "culture", "artworkType"],
    "default_color": "department",
    "range_column": "",
    "label_column": "title",
    "image_column": "primaryImageSmall",
    "embedding_mode": "text-gemini",
    "reducer": "umap",
    "umap_n_neighbors": 20,
    "umap_min_dist": 0.35,
    "umap_metric": "cosine",
    "n_clusters": 8,
}
