CONFIG = {
    "name": "moma",
    "display_name": "MoMA Collection",
    "sample_size": 3000,
    "sample_seed": 42,
    "embedding_columns": ["Classification", "Department", "Gender", "Nationality"],
    "color_columns": ["Classification", "Department", "Gender"],
    "filter_columns": ["Classification", "Department", "Gender"],
    "tooltip_columns": ["Title", "Artist", "Date", "Medium", "Classification", "Department", "Nationality"],
    "default_color": "Classification",
    "range_column": "",
    "label_column": "Title",
    "image_column": "ThumbnailURL",
    "embedding_mode": "text-gemini",
    "reducer": "umap",
    "umap_n_neighbors": 20,
    "umap_min_dist": 0.35,
    "umap_metric": "cosine",
    "n_clusters": 8,
}
