CONFIG = {
    "name": "movies",
    "display_name": "IMDb Top 1000 Movies",
    "sample_size": 0,
    "sample_seed": 42,
    "embedding_columns": ["IMDB_Rating", "Meta_score", "No_of_Votes", "Runtime_min", "Genre_Primary", "Certificate"],
    "color_columns": ["Genre_Primary", "Certificate"],
    "filter_columns": ["Genre_Primary", "Certificate"],
    "tooltip_columns": ["Series_Title", "Released_Year", "Genre", "IMDB_Rating", "Meta_score", "Director", "Runtime_min", "Gross"],
    "default_color": "Genre_Primary",
    "range_column": "IMDB_Rating",
    "label_column": "Series_Title",
    "image_column": "Poster_Link",
    "embedding_mode": "text-gemini",
    "reducer": "umap",
    "umap_n_neighbors": 20,
    "umap_min_dist": 0.35,
    "umap_metric": "cosine",
    "n_clusters": 6,
}
