CONFIG = {
    "name": "pokemon",
    "display_name": "Pokemon",
    "sample_size": 900,
    "sample_seed": 42,
    "embedding_columns": ["HP", "Attack", "Defense", "Sp. Atk", "Sp. Def", "Speed", "Type 1", "Type 2"],
    "color_columns": ["Type 1", "Generation_str", "Legendary"],
    "filter_columns": ["Type 1", "Type 2", "Generation_str", "Legendary"],
    "tooltip_columns": ["Name", "Type 1", "Type 2", "HP", "Attack", "Defense", "Sp. Atk", "Sp. Def", "Speed", "Total"],
    "default_color": "Type 1",
    "range_column": "Total",
    "label_column": "Name",
    "image_column": "image_url",
    "embedding_mode": "text-gemini",
    "reducer": "umap",
    "umap_n_neighbors": 20,
    "umap_min_dist": 0.35,
    "umap_metric": "cosine",
    "n_clusters": 6,
}
